// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AppointmentDiagnosis
    {
        /// <summary>
        /// Initializes a new instance of the AppointmentDiagnosis class.
        /// </summary>
        public AppointmentDiagnosis()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppointmentDiagnosis class.
        /// </summary>
        /// <param name="diagnosisid">A unique ID related to this
        /// diagnosis.</param>
        /// <param name="diagnosisdescription">A description of this
        /// diagnosis.</param>
        /// <param name="diagnosisrawcode">The raw ICD-9 code. This will
        /// migrate to ICD-10 in the future.</param>
        /// <param name="diagnosiscategory">The category for this
        /// diagnosis.</param>
        /// <param name="deleteddiagnosis">In certain cases, diagnoses may be
        /// added and then removed from a particular claim. In normal
        /// circumstances, this will be false. However, if a diagnosis was
        /// removed, this will be true.
        /// </param>
        /// <param name="diagnosiscodeset">Either ICD9 or ICD10.</param>
        public AppointmentDiagnosis(int? diagnosisid = default(int?), string diagnosisdescription = default(string), string diagnosisrawcode = default(string), string diagnosiscategory = default(string), string deleteddiagnosis = default(string), string diagnosiscodeset = default(string))
        {
            Diagnosisid = diagnosisid;
            Diagnosisdescription = diagnosisdescription;
            Diagnosisrawcode = diagnosisrawcode;
            Diagnosiscategory = diagnosiscategory;
            Deleteddiagnosis = deleteddiagnosis;
            Diagnosiscodeset = diagnosiscodeset;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets a unique ID related to this diagnosis.
        /// </summary>
        [JsonProperty(PropertyName = "diagnosisid")]
        public int? Diagnosisid { get; set; }

        /// <summary>
        /// Gets or sets a description of this diagnosis.
        /// </summary>
        [JsonProperty(PropertyName = "diagnosisdescription")]
        public string Diagnosisdescription { get; set; }

        /// <summary>
        /// Gets or sets the raw ICD-9 code. This will migrate to ICD-10 in the
        /// future.
        /// </summary>
        [JsonProperty(PropertyName = "diagnosisrawcode")]
        public string Diagnosisrawcode { get; set; }

        /// <summary>
        /// Gets or sets the category for this diagnosis.
        /// </summary>
        [JsonProperty(PropertyName = "diagnosiscategory")]
        public string Diagnosiscategory { get; set; }

        /// <summary>
        /// Gets or sets in certain cases, diagnoses may be added and then
        /// removed from a particular claim. In normal circumstances, this will
        /// be false. However, if a diagnosis was removed, this will be true.
        ///
        /// </summary>
        [JsonProperty(PropertyName = "deleteddiagnosis")]
        public string Deleteddiagnosis { get; set; }

        /// <summary>
        /// Gets or sets either ICD9 or ICD10.
        /// </summary>
        [JsonProperty(PropertyName = "diagnosiscodeset")]
        public string Diagnosiscodeset { get; set; }

    }
}
