// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AppointmentProcedure
    {
        /// <summary>
        /// Initializes a new instance of the AppointmentProcedure class.
        /// </summary>
        public AppointmentProcedure()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppointmentProcedure class.
        /// </summary>
        /// <param name="procedurecategory">The category name associated with
        /// this procedure.</param>
        /// <param name="allowablemin">The minimum amount expected from payer
        /// for all services from this procedure.</param>
        /// <param name="proceduredescription">A description of this
        /// procedure.</param>
        /// <param name="chargeamount">The amount charged for this
        /// procedure.</param>
        /// <param name="transactionid">The ID of the last transaction
        /// associated with the claim.</param>
        /// <param name="procedurecode">The CPT code associated with this
        /// procedure.</param>
        /// <param name="allowablemax">The maximum amount expected from payer
        /// for all services from this procedure.</param>
        /// <param name="allowableamount">The total amount expected from payer
        /// for all services from this procedure.</param>
        public AppointmentProcedure(string procedurecategory = default(string), string allowablemin = default(string), string proceduredescription = default(string), string chargeamount = default(string), int? transactionid = default(int?), string procedurecode = default(string), string allowablemax = default(string), string allowableamount = default(string))
        {
            Procedurecategory = procedurecategory;
            Allowablemin = allowablemin;
            Proceduredescription = proceduredescription;
            Chargeamount = chargeamount;
            Transactionid = transactionid;
            Procedurecode = procedurecode;
            Allowablemax = allowablemax;
            Allowableamount = allowableamount;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the category name associated with this procedure.
        /// </summary>
        [JsonProperty(PropertyName = "procedurecategory")]
        public string Procedurecategory { get; set; }

        /// <summary>
        /// Gets or sets the minimum amount expected from payer for all
        /// services from this procedure.
        /// </summary>
        [JsonProperty(PropertyName = "allowablemin")]
        public string Allowablemin { get; set; }

        /// <summary>
        /// Gets or sets a description of this procedure.
        /// </summary>
        [JsonProperty(PropertyName = "proceduredescription")]
        public string Proceduredescription { get; set; }

        /// <summary>
        /// Gets or sets the amount charged for this procedure.
        /// </summary>
        [JsonProperty(PropertyName = "chargeamount")]
        public string Chargeamount { get; set; }

        /// <summary>
        /// Gets or sets the ID of the last transaction associated with the
        /// claim.
        /// </summary>
        [JsonProperty(PropertyName = "transactionid")]
        public int? Transactionid { get; set; }

        /// <summary>
        /// Gets or sets the CPT code associated with this procedure.
        /// </summary>
        [JsonProperty(PropertyName = "procedurecode")]
        public string Procedurecode { get; set; }

        /// <summary>
        /// Gets or sets the maximum amount expected from payer for all
        /// services from this procedure.
        /// </summary>
        [JsonProperty(PropertyName = "allowablemax")]
        public string Allowablemax { get; set; }

        /// <summary>
        /// Gets or sets the total amount expected from payer for all services
        /// from this procedure.
        /// </summary>
        [JsonProperty(PropertyName = "allowableamount")]
        public string Allowableamount { get; set; }

    }
}
