// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AppointmentCopayInformation
    {
        /// <summary>
        /// Initializes a new instance of the AppointmentCopayInformation
        /// class.
        /// </summary>
        public AppointmentCopayInformation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppointmentCopayInformation
        /// class.
        /// </summary>
        /// <param name="insurancecopay">The expected copay based on the
        /// patient's primary insurance and appointment type.</param>
        /// <param name="collectedforappointment">Copay payments that have
        /// already been collected for this specific appointment.</param>
        /// <param name="collectedforother">Copay payments that have already
        /// been collected for this patient, but that have not yet been applied
        /// to any specific appointment.</param>
        public AppointmentCopayInformation(string insurancecopay = default(string), string collectedforappointment = default(string), string collectedforother = default(string))
        {
            Insurancecopay = insurancecopay;
            Collectedforappointment = collectedforappointment;
            Collectedforother = collectedforother;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the expected copay based on the patient's primary
        /// insurance and appointment type.
        /// </summary>
        [JsonProperty(PropertyName = "insurancecopay")]
        public string Insurancecopay { get; set; }

        /// <summary>
        /// Gets or sets copay payments that have already been collected for
        /// this specific appointment.
        /// </summary>
        [JsonProperty(PropertyName = "collectedforappointment")]
        public string Collectedforappointment { get; set; }

        /// <summary>
        /// Gets or sets copay payments that have already been collected for
        /// this patient, but that have not yet been applied to any specific
        /// appointment.
        /// </summary>
        [JsonProperty(PropertyName = "collectedforother")]
        public string Collectedforother { get; set; }

    }
}
