// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AppointmentInformationList
    {
        /// <summary>
        /// Initializes a new instance of the AppointmentInformationList class.
        /// </summary>
        public AppointmentInformationList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppointmentInformationList class.
        /// </summary>
        public AppointmentInformationList(int totalCount, IList<AppointmentInformation> appointments)
        {
            TotalCount = totalCount;
            Appointments = appointments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalcount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appointments")]
        public IList<AppointmentInformation> Appointments { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Appointments == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Appointments");
            }
        }
    }
}
