// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AppointmentTypeInformationList
    {
        /// <summary>
        /// Initializes a new instance of the AppointmentTypeInformationList
        /// class.
        /// </summary>
        public AppointmentTypeInformationList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AppointmentTypeInformationList
        /// class.
        /// </summary>
        public AppointmentTypeInformationList(int totalCount, IList<AppointmentTypeInformation> appointmenttypes)
        {
            TotalCount = totalCount;
            Appointmenttypes = appointmenttypes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalcount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appointmenttypes")]
        public IList<AppointmentTypeInformation> Appointmenttypes { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Appointmenttypes == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Appointmenttypes");
            }
            if (Appointmenttypes != null)
            {
                foreach (var element in Appointmenttypes)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
