// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ClaimsList
    {
        /// <summary>
        /// Initializes a new instance of the ClaimsList class.
        /// </summary>
        public ClaimsList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClaimsList class.
        /// </summary>
        public ClaimsList(int totalCount, IList<AppointmentClaim> claims)
        {
            TotalCount = totalCount;
            Claims = claims;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalcount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "claims")]
        public IList<AppointmentClaim> Claims { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Claims == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Claims");
            }
        }
    }
}
