// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CreatePatientProblemResponse
    {
        /// <summary>
        /// Initializes a new instance of the CreatePatientProblemResponse
        /// class.
        /// </summary>
        public CreatePatientProblemResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CreatePatientProblemResponse
        /// class.
        /// </summary>
        /// <param name="success">Whether the operation was successful or
        /// not.</param>
        /// <param name="problemId">If successful, the athena ID of the newly
        /// created problem</param>
        /// <param name="errormessage">If the operation failed, this will
        /// contain any error messages.</param>
        public CreatePatientProblemResponse(bool success, int? problemId = default(int?), string errormessage = default(string))
        {
            ProblemId = problemId;
            Success = success;
            Errormessage = errormessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets if successful, the athena ID of the newly created
        /// problem
        /// </summary>
        [JsonProperty(PropertyName = "problemid")]
        public int? ProblemId { get; set; }

        /// <summary>
        /// Gets or sets whether the operation was successful or not.
        /// </summary>
        [JsonProperty(PropertyName = "success")]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or sets if the operation failed, this will contain any error
        /// messages.
        /// </summary>
        [JsonProperty(PropertyName = "errormessage")]
        public string Errormessage { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
