// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DepartmentInformationList
    {
        /// <summary>
        /// Initializes a new instance of the DepartmentInformationList class.
        /// </summary>
        public DepartmentInformationList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DepartmentInformationList class.
        /// </summary>
        public DepartmentInformationList(int totalCount, IList<DepartmentInformation> departments)
        {
            TotalCount = totalCount;
            Departments = departments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalcount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "departments")]
        public IList<DepartmentInformation> Departments { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Departments == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Departments");
            }
            if (Departments != null)
            {
                foreach (var element in Departments)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
