// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EncounterInformation
    {
        /// <summary>
        /// Initializes a new instance of the EncounterInformation class.
        /// </summary>
        public EncounterInformation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EncounterInformation class.
        /// </summary>
        /// <param name="encounterId">Athena ID for this encounter</param>
        /// <param name="appointmentid">Athena appointment ID resulting in this
        /// encounter</param>
        /// <param name="departmentId">The athena department ID of this
        /// encounter</param>
        /// <param name="encountervisitname">The visit name for this
        /// encounter</param>
        /// <param name="encountertype">Type of encounter (FLOWSHEET,
        /// ORDERSONLY, VISIT, etc.). By default only VISIT and ORDERSONLY are
        /// shown, use INCLUDEALLtypeS flag to see others.
        /// </param>
        /// <param name="status">Status of this encounter (CLOSED, OPEN, PEND).
        /// By default only OPEN, CLOSED, and REVIEW statuses are shown, use
        /// INCLUDEALLSTATUSES flag to see others.
        /// </param>
        /// <param name="patientlocationid">Athena ID for the patient
        /// location</param>
        /// <param name="patientlocation">Patient location</param>
        /// <param name="patientstatusid">Athena ID for the patient
        /// status</param>
        /// <param name="patientstatus">Patient status</param>
        /// <param name="encounterdate">Date when this encounter
        /// occured</param>
        /// <param name="stage">Last stage of the encounter</param>
        /// <param name="providerid">The ID of the provider for this
        /// encounter</param>
        /// <param name="providerfirstname">First name of the provider for this
        /// encounter</param>
        /// <param name="providerlastname">Last name of the provider for this
        /// encounter</param>
        /// <param name="providerphone">Phone number of the provider for this
        /// encounter</param>
        /// <param name="lastupdated">The date the encounter was last
        /// updated</param>
        public EncounterInformation(int encounterId, IList<PatientEncounterDiagnosis> diagnoses, int? appointmentid = default(int?), int? departmentId = default(int?), string encountervisitname = default(string), string encountertype = default(string), string status = default(string), int? patientlocationid = default(int?), string patientlocation = default(string), int? patientstatusid = default(int?), string patientstatus = default(string), string encounterdate = default(string), string stage = default(string), int? providerid = default(int?), string providerfirstname = default(string), string providerlastname = default(string), string providerphone = default(string), string lastupdated = default(string))
        {
            EncounterId = encounterId;
            Diagnoses = diagnoses;
            Appointmentid = appointmentid;
            DepartmentId = departmentId;
            Encountervisitname = encountervisitname;
            Encountertype = encountertype;
            Status = status;
            Patientlocationid = patientlocationid;
            Patientlocation = patientlocation;
            Patientstatusid = patientstatusid;
            Patientstatus = patientstatus;
            Encounterdate = encounterdate;
            Stage = stage;
            Providerid = providerid;
            Providerfirstname = providerfirstname;
            Providerlastname = providerlastname;
            Providerphone = providerphone;
            Lastupdated = lastupdated;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets athena ID for this encounter
        /// </summary>
        [JsonProperty(PropertyName = "encounterid")]
        public int EncounterId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "diagnoses")]
        public IList<PatientEncounterDiagnosis> Diagnoses { get; set; }

        /// <summary>
        /// Gets or sets athena appointment ID resulting in this encounter
        /// </summary>
        [JsonProperty(PropertyName = "appointmentid")]
        public int? Appointmentid { get; set; }

        /// <summary>
        /// Gets or sets the athena department ID of this encounter
        /// </summary>
        [JsonProperty(PropertyName = "departmentid")]
        public int? DepartmentId { get; set; }

        /// <summary>
        /// Gets or sets the visit name for this encounter
        /// </summary>
        [JsonProperty(PropertyName = "encountervisitname")]
        public string Encountervisitname { get; set; }

        /// <summary>
        /// Gets or sets type of encounter (FLOWSHEET, ORDERSONLY, VISIT,
        /// etc.). By default only VISIT and ORDERSONLY are shown, use
        /// INCLUDEALLtypeS flag to see others.
        ///
        /// </summary>
        [JsonProperty(PropertyName = "encountertype")]
        public string Encountertype { get; set; }

        /// <summary>
        /// Gets or sets status of this encounter (CLOSED, OPEN, PEND). By
        /// default only OPEN, CLOSED, and REVIEW statuses are shown, use
        /// INCLUDEALLSTATUSES flag to see others.
        ///
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or sets athena ID for the patient location
        /// </summary>
        [JsonProperty(PropertyName = "patientlocationid")]
        public int? Patientlocationid { get; set; }

        /// <summary>
        /// Gets or sets patient location
        /// </summary>
        [JsonProperty(PropertyName = "patientlocation")]
        public string Patientlocation { get; set; }

        /// <summary>
        /// Gets or sets athena ID for the patient status
        /// </summary>
        [JsonProperty(PropertyName = "patientstatusid")]
        public int? Patientstatusid { get; set; }

        /// <summary>
        /// Gets or sets patient status
        /// </summary>
        [JsonProperty(PropertyName = "patientstatus")]
        public string Patientstatus { get; set; }

        /// <summary>
        /// Gets or sets date when this encounter occured
        /// </summary>
        [JsonProperty(PropertyName = "encounterdate")]
        public string Encounterdate { get; set; }

        /// <summary>
        /// Gets or sets last stage of the encounter
        /// </summary>
        [JsonProperty(PropertyName = "stage")]
        public string Stage { get; set; }

        /// <summary>
        /// Gets or sets the ID of the provider for this encounter
        /// </summary>
        [JsonProperty(PropertyName = "providerid")]
        public int? Providerid { get; set; }

        /// <summary>
        /// Gets or sets first name of the provider for this encounter
        /// </summary>
        [JsonProperty(PropertyName = "providerfirstname")]
        public string Providerfirstname { get; set; }

        /// <summary>
        /// Gets or sets last name of the provider for this encounter
        /// </summary>
        [JsonProperty(PropertyName = "providerlastname")]
        public string Providerlastname { get; set; }

        /// <summary>
        /// Gets or sets phone number of the provider for this encounter
        /// </summary>
        [JsonProperty(PropertyName = "providerphone")]
        public string Providerphone { get; set; }

        /// <summary>
        /// Gets or sets the date the encounter was last updated
        /// </summary>
        [JsonProperty(PropertyName = "lastupdated")]
        public string Lastupdated { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Diagnoses == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Diagnoses");
            }
            if (Diagnoses != null)
            {
                foreach (var element in Diagnoses)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
