// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LabResultList
    {
        /// <summary>
        /// Initializes a new instance of the LabResultList class.
        /// </summary>
        public LabResultList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LabResultList class.
        /// </summary>
        public LabResultList(int totalCount, IList<LabResult> results)
        {
            TotalCount = totalCount;
            Results = results;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalcount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "results")]
        public IList<LabResult> Results { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Results == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Results");
            }
            if (Results != null)
            {
                foreach (var element in Results)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
