// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class MessageResult
    {
        /// <summary>
        /// Initializes a new instance of the MessageResult class.
        /// </summary>
        public MessageResult()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageResult class.
        /// </summary>
        /// <param name="messagetype">The type of message that was
        /// attempted.</param>
        /// <param name="calltime">Date and time of the call attempt.</param>
        /// <param name="messageresultid">Id of the message attempt.</param>
        /// <param name="result">A description of what happened during the call
        /// attempt.</param>
        public MessageResult(string messagetype = default(string), string calltime = default(string), int? messageresultid = default(int?), string result = default(string))
        {
            Messagetype = messagetype;
            Calltime = calltime;
            Messageresultid = messageresultid;
            Result = result;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the type of message that was attempted.
        /// </summary>
        [JsonProperty(PropertyName = "messagetype")]
        public string Messagetype { get; set; }

        /// <summary>
        /// Gets or sets date and time of the call attempt.
        /// </summary>
        [JsonProperty(PropertyName = "calltime")]
        public string Calltime { get; set; }

        /// <summary>
        /// Gets or sets id of the message attempt.
        /// </summary>
        [JsonProperty(PropertyName = "messageresultid")]
        public int? Messageresultid { get; set; }

        /// <summary>
        /// Gets or sets a description of what happened during the call
        /// attempt.
        /// </summary>
        [JsonProperty(PropertyName = "result")]
        public string Result { get; set; }

    }
}
