// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PatientDeparmentStatus
    {
        /// <summary>
        /// Initializes a new instance of the PatientDeparmentStatus class.
        /// </summary>
        public PatientDeparmentStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PatientDeparmentStatus class.
        /// </summary>
        /// <param name="departmentid">The ID of a department that this patient
        /// is registered in.</param>
        /// <param name="primaryproviderid">The "primary" provider for this
        /// patient, if set.</param>
        /// <param name="status">The "status" of the patient, one of active,
        /// inactive, prospective, or deleted.</param>
        public PatientDeparmentStatus(int? departmentid = default(int?), string primaryproviderid = default(string), string status = default(string))
        {
            Departmentid = departmentid;
            Primaryproviderid = primaryproviderid;
            Status = status;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the ID of a department that this patient is registered
        /// in.
        /// </summary>
        [JsonProperty(PropertyName = "departmentid")]
        public int? Departmentid { get; set; }

        /// <summary>
        /// Gets or sets the "primary" provider for this patient, if set.
        /// </summary>
        [JsonProperty(PropertyName = "primaryproviderid")]
        public string Primaryproviderid { get; set; }

        /// <summary>
        /// Gets or sets the "status" of the patient, one of active, inactive,
        /// prospective, or deleted.
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

    }
}
