// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PatientBalanceInformation
    {
        /// <summary>
        /// Initializes a new instance of the PatientBalanceInformation class.
        /// </summary>
        public PatientBalanceInformation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PatientBalanceInformation class.
        /// </summary>
        /// <param name="contracts">Information related to existing credit card
        /// contracts.</param>
        /// <param name="providergroupid">Athena ID for this financial
        /// group.</param>
        /// <param name="departmentlist">Comma separated list of department IDs
        /// that belong to this group</param>
        /// <param name="balance">Balance for this provider group.</param>
        /// <param name="cleanbalance">Indicates whether the balance is
        /// associated with a contract, payment plan, or collections
        /// agency.</param>
        /// <param name="collectionsbalance">The outstanding amount associated
        /// with a collections agency.</param>
        /// <param name="paymentplanbalance">The outstanding amount associated
        /// with a payment plan.</param>
        public PatientBalanceInformation(IList<PatientBalanceContract> contracts = default(IList<PatientBalanceContract>), string providergroupid = default(string), string departmentlist = default(string), string balance = default(string), bool? cleanbalance = default(bool?), string collectionsbalance = default(string), string paymentplanbalance = default(string))
        {
            Contracts = contracts;
            Providergroupid = providergroupid;
            Departmentlist = departmentlist;
            Balance = balance;
            Cleanbalance = cleanbalance;
            Collectionsbalance = collectionsbalance;
            Paymentplanbalance = paymentplanbalance;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets information related to existing credit card contracts.
        /// </summary>
        [JsonProperty(PropertyName = "contracts")]
        public IList<PatientBalanceContract> Contracts { get; set; }

        /// <summary>
        /// Gets or sets athena ID for this financial group.
        /// </summary>
        [JsonProperty(PropertyName = "providergroupid")]
        public string Providergroupid { get; set; }

        /// <summary>
        /// Gets or sets comma separated list of department IDs that belong to
        /// this group
        /// </summary>
        [JsonProperty(PropertyName = "departmentlist")]
        public string Departmentlist { get; set; }

        /// <summary>
        /// Gets or sets balance for this provider group.
        /// </summary>
        [JsonProperty(PropertyName = "balance")]
        public string Balance { get; set; }

        /// <summary>
        /// Gets or sets indicates whether the balance is associated with a
        /// contract, payment plan, or collections agency.
        /// </summary>
        [JsonProperty(PropertyName = "cleanbalance")]
        public bool? Cleanbalance { get; set; }

        /// <summary>
        /// Gets or sets the outstanding amount associated with a collections
        /// agency.
        /// </summary>
        [JsonProperty(PropertyName = "collectionsbalance")]
        public string Collectionsbalance { get; set; }

        /// <summary>
        /// Gets or sets the outstanding amount associated with a payment plan.
        /// </summary>
        [JsonProperty(PropertyName = "paymentplanbalance")]
        public string Paymentplanbalance { get; set; }

    }
}
