// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PatientMedicalHistory
    {
        /// <summary>
        /// Initializes a new instance of the PatientMedicalHistory class.
        /// </summary>
        public PatientMedicalHistory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PatientMedicalHistory class.
        /// </summary>
        /// <param name="sectionnote">Additional notes for the entire medical
        /// history section, if any</param>
        public PatientMedicalHistory(string sectionnote = default(string), IList<PatientMedicalHistoryQuestion> questions = default(IList<PatientMedicalHistoryQuestion>))
        {
            Sectionnote = sectionnote;
            Questions = questions;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets additional notes for the entire medical history
        /// section, if any
        /// </summary>
        [JsonProperty(PropertyName = "sectionnote")]
        public string Sectionnote { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "questions")]
        public IList<PatientMedicalHistoryQuestion> Questions { get; set; }

    }
}
