// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PatientCreatedResponse
    {
        /// <summary>
        /// Initializes a new instance of the PatientCreatedResponse class.
        /// </summary>
        public PatientCreatedResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PatientCreatedResponse class.
        /// </summary>
        public PatientCreatedResponse(int? patientId = default(int?))
        {
            PatientId = patientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "patientid")]
        public int? PatientId { get; set; }

    }
}
