// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProblemsList
    {
        /// <summary>
        /// Initializes a new instance of the ProblemsList class.
        /// </summary>
        public ProblemsList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProblemsList class.
        /// </summary>
        public ProblemsList(int totalCount, IList<PatientProblem> problems)
        {
            TotalCount = totalCount;
            Problems = problems;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalcount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "problems")]
        public IList<PatientProblem> Problems { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Problems == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Problems");
            }
            if (Problems != null)
            {
                foreach (var element in Problems)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
