// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AndriiKurdiumov.AuthenaHealth.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProvidersInformationList
    {
        /// <summary>
        /// Initializes a new instance of the ProvidersInformationList class.
        /// </summary>
        public ProvidersInformationList()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProvidersInformationList class.
        /// </summary>
        public ProvidersInformationList(int totalCount, IList<ProviderInformation> providers = default(IList<ProviderInformation>))
        {
            TotalCount = totalCount;
            Providers = providers;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalcount")]
        public int TotalCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "providers")]
        public IList<ProviderInformation> Providers { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
